truncate table person_details cascade;
truncate table address_details cascade;
truncate table category_details cascade;
truncate table company_details cascade;
truncate table source_details cascade;
truncate table person_category cascade;
truncate table person_event cascade;
truncate table person_source cascade;
truncate table log cascade;
